name: Go

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: download dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...
    
    - name: login to dockerhub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
      
    - name: build image
      run: |
        docker build \
        -t muktiarafi/ticketing-tickets:latest \
        -t muktiarafi/ticketing-tickets:$GITHUB_SHA \
        .

    - name: push
      run: |
        docker push muktiarafi/ticketing-tickets:latest
        docker push muktiarafi/ticketing-tickets:$GITHUB_SHA
